### ISSUE TITLE
Announce of the tool to validate SONATA circuits.

### ISSUE THREAD

**Issue by asanin-epfl** [AllenInstitute/sonata#123]
We have created a tool to validate SONATA circuits https://github.com/BlueBrain/snap/#tools. Should we mention this tool in [SONATA_DEVELOPER_GUIDE.md](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md)?

**Comment by asanin-epfl** [comment]
cc @kaeldai @pgleeson

**Comment by asanin-epfl** [comment]
Here is an example of running it with one of examples circuit in this repo:
```
(venv) bb-fvfxv5s0j1wt:snap sanin$ bluepysnap validate /workspace/sonata/examples/300_cells/circuit_config.json 
Traceback (most recent call last):
  File "/workspace/snap/venv/bin/bluepysnap", line 11, in <module>
    load_entry_point('bluepysnap', 'console_scripts', 'bluepysnap')()
  File "/workspace/snap/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/snap/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/workspace/snap/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/snap/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/snap/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/workspace/snap/bluepysnap/cli.py", line 20, in validate_cli
    validate(config_file)
  File "/workspace/snap/bluepysnap/circuit_validation.py", line 587, in validate
    errors = _check_populations(config)
  File "/workspace/snap/bluepysnap/circuit_validation.py", line 564, in _check_populations
    errors += _check_nodes_population(nodes_dict, config)
  File "/workspace/snap/bluepysnap/circuit_validation.py", line 354, in _check_nodes_population
    population['node_group_id'], population['node_group_index'], population)
  File "/workspace/snap/bluepysnap/circuit_validation.py", line 233, in _check_multi_groups
    if _get_group_size(group) < max_id:
  File "/workspace/snap/bluepysnap/circuit_validation.py", line 214, in _get_group_size
    raise BluepySnapError('Empty group {}'.format(group_h5))
bluepysnap.exceptions.BluepySnapError: Empty group <HDF5 group "/nodes/external/0" (0 members)>
```

**Comment by pgleeson** [comment]
Thanks for letting us know @asanin-epfl. I'll try it out.

**Comment by asanin-epfl** [comment]
Great. It currently misses validation of `node_types_file` csv file but I'm working on it. It soon will be merged https://github.com/BlueBrain/snap/pull/81

**Comment by asanin-epfl** [comment]
Here is the log with the latest master of bluepysnap
```
FATAL: Group external/0 of .../sonata/examples/300_cells/network/external_nodes.h5 misses required fields: ['model_template']
```
