### ISSUE TITLE
NEURON mechanisms not found

### ISSUE THREAD

**Issue by maartensc** [AllenInstitute/sonata#131]
Hi, I'm new with bmtk, and when trying to run bionet.py for the example folders, I get the error that NEURON mechanisms are not found, with the eventual ValueError that the argument is not a density mechanism name. 

```python run_bionet.py 
2022-01-26 18:50:02,078 [INFO] Created log file
NEURON mechanisms not found in ../shared_components/mechanisms.
2022-01-26 18:50:02,219 [INFO] Building cells.
Traceback (most recent call last):
  File "run_bionet.py", line 17, in <module>
    run('config.json')
  File "run_bionet.py", line 9, in run
    sim = bionet.BioSimulator.from_config(conf, network=net)
  File "/users/mns/mschelle/Desktop/PenO/IMP/miniconda3/envs/bmtk/lib/python3.7/site-packages/bmtk/simulator/bionet/biosimulator.py", line 402, in from_config
    network.build_nodes()
  File "/users/mns/mschelle/Desktop/PenO/IMP/miniconda3/envs/bmtk/lib/python3.7/site-packages/bmtk/simulator/bionet/bionetwork.py", line 163, in build_nodes
    cell = self._build_cell(bionode=node, population_name=node_pop.name)
  File "/users/mns/mschelle/Desktop/PenO/IMP/miniconda3/envs/bmtk/lib/python3.7/site-packages/bmtk/simulator/bionet/bionetwork.py", line 146, in _build_cell
    cell = self._model_type_map[bionode.model_type](bionode, population_name=population_name, bionetwork=self)
  File "/users/mns/mschelle/Desktop/PenO/IMP/miniconda3/envs/bmtk/lib/python3.7/site-packages/bmtk/simulator/bionet/biocell.py", line 74, in __init__
    super(BioCell, self).__init__(node=node, population_name=population_name, network=bionetwork)
  File "/users/mns/mschelle/Desktop/PenO/IMP/miniconda3/envs/bmtk/lib/python3.7/site-packages/bmtk/simulator/bionet/cell.py", line 54, in __init__
    self._hobj = node.load_cell()
  File "/users/mns/mschelle/Desktop/PenO/IMP/miniconda3/envs/bmtk/lib/python3.7/site-packages/bmtk/simulator/bionet/sonata_adaptors.py", line 70, in load_cell
    hobj = cell_fnc(self, template_name, dynamics_params)
  File "/users/mns/mschelle/Desktop/PenO/IMP/miniconda3/envs/bmtk/lib/python3.7/site-packages/bmtk/simulator/bionet/default_setters/cell_models.py", line 457, in NMLLoad
    sec.insert(prop_obj.id)
ValueError: argument not a density mechanism name.
```

I am working with python 3.7.11, bmtk 1.0.1, sonata 0.0.2, and neuron 8.0.0. I suppose something is wrong with the installed neuron version, but I can't find what. Do you have any ideas?

**Comment by kaeldai** [comment]
Hi @maartensc - this problem usually occurs because the Allen Institute models uses some special channel mechanisms that need to be precompiled using the nrnivmodl command. If you open a command line in the ../shared_components/mechanisms/ folder and run the following:
```bash
$ nrnivmodl modfiles
```
NEURON should compile the mod files and create a (usually called) x86_64/ folder. After this bmtk should be able to build the cells models.

Thanks,
Kael

**Comment by maartensc** [comment]
Hi Kael,

Now it indeed runs smoothly, thank you very much!

Maarten
